from Agent.state import State
from Tools.filesystem import FileSystemTools


def Executer(state: State):
    """
    Executor Node.

    Takes the plan generated by the Planner Node and executes
    the current task using the appropriate filesystem operation.

    Supports task dependencies using:
        "path_from_task": <task_id>

    Example:
        Task 1 -> find_file("resume.pdf")
        Task 2 -> open_file(path_from_task=1)

    The executor resolves Task 2 to:
        open_file(path="NewFolder/resume.pdf")
    """

    CurrentTaskIndex = state["current_task"]
    Plan = state["plan"]
    if CurrentTaskIndex >= len(Plan):
        return {
            "status": "completed",
            "error": None
        }
    Task = Plan[CurrentTaskIndex]
    Action = Task["action"]
    Arguments = dict(Task.get("arguments", {}))
    History = list(state.get("execution_history", []))
    if "path_from_task" in Arguments:
        DependencyTaskID = Arguments["path_from_task"]
        DependencyResult = None
        for HistoryItem in History:

            if HistoryItem["task_id"] == DependencyTaskID:

                DependencyResult = HistoryItem["result"]

                break
        if DependencyResult is None:

            return {
                "execution_history": History,
                "status": "failed",
                "error": (
                    f"Could not find the result of "
                    f"task {DependencyTaskID}"
                )
            }
        Matches = DependencyResult.get("matches", [])
        if not Matches:
            return {
                "execution_history": History,
                "status": "failed",
                "error": (
                    f"Task {DependencyTaskID} "
                    f"did not return a file path."
                )
            }
        Arguments.pop("path_from_task")

        Arguments["path"] = Matches[0]
    filesystem = FileSystemTools(
        state["sandbox"]
    )
    tools = {
        "create_file": filesystem.create_file,
        "read_file": filesystem.read_file,
        "update_file": filesystem.update_file,
        "create_folder": filesystem.create_folder,
        "list_folder": filesystem.list_folder,
        "update_folder": filesystem.update_folder,
        "open_file": filesystem.open_file,
        "find_file": filesystem.find_file
    }
    if Action not in tools:

        return {
            "execution_history": History,
            "status": "failed",
            "error": (
                f"Unknown filesystem action: {Action}"
            )
        }
    try:

        Result = tools[Action](**Arguments)

    except Exception as e:
        History.append({
            "task_id": Task["id"],
            "action": Action,
            "arguments": Arguments,
            "result": {
                "success": False,
                "error": str(e)
            }
        })
        return {
            "execution_history": History,
            "status": "failed",
            "error": str(e)
        }
    History.append({
        "task_id": Task["id"],
        "action": Action,
        "arguments": Arguments,
        "result": Result
    })
    if not Result.get("success", False):

        return {
            "execution_history": History,
            "status": "failed",
            "error": Result.get(
                "error",
                "Task execution failed"
            )
        }
    NextTask = CurrentTaskIndex + 1
    if NextTask >= len(Plan):
        status = "executed"
    else:
        status = "executing"
    return {
        "current_task": NextTask,
        "execution_history": History,
        "status": status,
        "error": None
    }